services:
  - type: web
    name: mexc-volume-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Mexcnewbot.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mexc-bot-db  # <-- Имя вашей базы данных
          property: connectionString
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MY_USER_ID
        sync: false
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_SECRET_KEY
        sync: false

databases:
  - name: mexc-bot-db  # <-- ДОБАВЬТЕ ЭТОТ РАЗДЕЛ
    plan: free
    databaseName: mexc_bot
    user: mexc_user
